// https://None.appspot.com/bug?id=9107190ad1f86497fbba349aca969ecd05914a5f
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

static long syz_open_dev(volatile long a0, volatile long a1, volatile long a2)
{
  if (a0 == 0xc || a0 == 0xb) {
    char buf[128];
    sprintf(buf, "/dev/%s/%d:%d", a0 == 0xc ? "char" : "block", (uint8_t)a1,
            (uint8_t)a2);
    return open(buf, O_RDWR, 0);
  } else {
    char buf[1024];
    char* hash;
    strncpy(buf, (char*)a0, sizeof(buf) - 1);
    buf[sizeof(buf) - 1] = 0;
    while ((hash = strchr(buf, '#'))) {
      *hash = '0' + (char)(a1 % 10);
      a1 /= 10;
    }
    return open(buf, a2, 0);
  }
}

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
  syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  intptr_t res = 0;
  memcpy((void*)0x20000100, "/dev/sg#\000", 9);
  res = -1;
  res = syz_open_dev(0x20000100, 0, 0);
  if (res != -1)
    r[0] = res;
  *(uint32_t*)0x20000680 = 0x53;
  *(uint32_t*)0x20000684 = 0;
  *(uint8_t*)0x20000688 = 0xF;
  *(uint8_t*)0x20000689 = 0;
  *(uint16_t*)0x2000068a = 0;
  *(uint32_t*)0x2000068c = 0;
  *(uint64_t*)0x20000690 = 0;
  *(uint64_t*)0x20000698 = 0x20000000;
  memcpy((void*)0x20000000,
         "\x7f\x31\x14\xf0\xd7\x05\x61\xd8\x1f\xf0\x39\x0a\x45\x52\x3a\x01\xc6"
         "\x40\x27\xb6\xe2\x4b\xb3\x55\x57\x95\x86\x10\xa3\x66\xe1\xe3\x8f\x96"
         "\x92\xe5\xdb\x4c\x5d\x29\xed\x88\x65\x62\x6b\xf8\x43\xf9\x55\x1d\x58"
         "\xd7\x06\x04\xf7\x84\x0e\xbd\xef\x73\x93\xbb\x00\x43\xb0\xc2\xbb\x97"
         "\x3b\x0b\xc3\xd6\x52\x11\x44\xa5\x97\xe3\xcc\xe3\x12\xa0\x4c\xe0\x7a"
         "\x18\x96\xb4\x2b\xd2\xe1\x02\x4d\x9c\x71\x44\x80\x36\x43\xa6\xf7\xec"
         "\xd8\x01\xa0\x19\x92\x89\xbc\x3e\x78\x4c\x57\xcb\x09\x35\x3c\xf1\xe9"
         "\x90\xc5\xc5\x5b\x12\x8a\x7d\xb0\x95\xee\x8b\x5c\x32\xfe\xc9\xe1\x83"
         "\x29\xaf\x6c\xac\xcd\xfb\x3a\xde\x38\xdf\x2e\x95\x2a\xcb\x4a\xae\x41"
         "\x85\x7a\x91\x02\x0e\xaf\x6d\xa7\x8d\xe6\x2f\xbc\xc2\xbb\xf1\xd8\x6c"
         "\x0f\x7f\x0c\xbc\x37\x32\xd5\xf2\x75\x49\xbf\xf2\x9e\xbf\x33\x7d\x8c"
         "\x13\xc4\xdd\xbc\x58\xa9\xf9\xe5\x90\x36\x2d\xb3\xcd\x30\x80\xed",
         203);
  *(uint64_t*)0x200006a0 = 0;
  *(uint32_t*)0x200006a8 = 3;
  *(uint32_t*)0x200006ac = 0x10020;
  *(uint32_t*)0x200006b0 = 3;
  *(uint64_t*)0x200006b4 = 0;
  *(uint8_t*)0x200006bc = 0;
  *(uint8_t*)0x200006bd = 0;
  *(uint8_t*)0x200006be = 0;
  *(uint8_t*)0x200006bf = 0;
  *(uint16_t*)0x200006c0 = 0;
  *(uint16_t*)0x200006c2 = 0;
  *(uint32_t*)0x200006c4 = 0;
  *(uint32_t*)0x200006c8 = 0;
  *(uint32_t*)0x200006cc = 0;
  syscall(__NR_ioctl, r[0], 0x2285, 0x20000680ul);
  return 0;
}
